#+TITLE: 211125_student_topic_proposals

* Αλέξανδρος Κουμπλής:
** version 1
Παράλληλη αναπαραγωγή δύο ή και παραπάνω μελωδιών ταυτόχρονα.
Μελωδίες με τον παράγοντα του τυχαίου.
Αλλαγή των χαρακτηριστικών του ήχου που παράγει το super collider.
Χρήση σταθερού ρυθμικού μοτίβου.
Χρήση white noise, ενσωματωμένο σε κάποιο ρυθμικό μοτίβο – ταυτόχρονη αναπαραγωγή.
** version 2

Θέλω να δημιουργήσω ένα πρόγραμμα στο super collider που να παράγει ένα μουσικό κομμάτι με τα εξής χαρακτηριστικά:

1. Στο κομμάτι αυτό παίζουν ταυτόχρονα δύο ή και περισσότερες μελωδίες.
2. Οι μελωδίες αυτές χρησιμοποιούν συναρτήσεις τυχαίου (random) για να καθορίσουν ορισμένα χαρακτηριστικά της δομής τους.
3. Οι ήχοι που απαρτίζουν τις μελωδίες έχουν διαφορετικά ποιοτικά χαρακτηριστικά (ηχοχρώματα).
4. Θέλω να προσθέσω μια συνοδεία που αποτελείται από ένα επαναλαμβανόμενο ρυθμικό μοτίβο.
5. Το ρυθμικό μοτίβο να χρησιμοποιεί την γεννήτρια WhiteNoise.

* Θοδωρής Νεοφώτιστος:
** version 1
Δημιουργία ήχων που να σχετίζονται με παραμέτρους που αφορούν το πυθαγόρειο θεώρημα. Πιο αναλυτικά, γνωρίζοντας ότι η μία γωνία είναι ορθή, ανάλογα με το μέτρο των άλλων δύο, θα δημιουργήσουμε ένα πρόγραμμα που να παράγει τους διάφορους ήχους.

** version 2
•	Θέλω να χρησιμοποιήσω το supercollider για να δημιουργήσω ήχους.
•	Γνωρίζω το Πυθαγόρειο Θεώρημα.
•	Το Πυθαγόρειο Θεώρημα αφορά ορθογώνια τρίγωνα.
•	Αλλάζω τις παραμέτρους που αφορούν το μέτρων των οξειών γωνιών.
•	Δημιουργώ ηχητικούς συνδυασμούς.

* Κώστας Φραντζής:

Προτεινόμενος τίτλος εργασίας:
Παραγωγή Κρουστικών αποκρίσεων σε περιβάλλον επαυξημένης ηχητικής ανα-παραγωγής (immersive - binaural audio)

Σύντομη περιγραφή:

Η εργασία φιλοδοξεί να δημιουργήσει ένα patch στο περιβάλλον του Supercollider το οποίο θα αναπαράγει κρουστικές αποκρίσεις (impulse responses) επιλεγμένων χώρων με ακουστικό ενδιαφέρον. Σε μια σύντομη περιγραφή της μεθοδολογίας που πρόκειται να ακολουθηθεί εντοπίζονται τα εξής στάδια:

Στάδιο 1: Επιλογή χώρων - καταγραφή IRs (sampling)
Στάδιο 2: Σχεδιασμός και προγραμματισμός περιέλιξης ηχητικού σήματος (convolution) στο περιβάλλον του SC
Στάδιο 3: Πειραματική εφαρμογή σε ηχητικά δείγματα

* Ιορδάνης Χατζηστυλλής
** version 1

Είσοδος ενός ή και παραπάνω μουσικών έργων στο πρόγραμμα. "Κομμάτιασμά" τους σε μικρά σε διάρκεια τμήματα. Αναπαραγωγή των τμημάτων αυτών με τυχαία σειρά και δημιουργία νέων μουσικών έργων.
** version 2

1. Εισάγω μουσικά έργα στο πρόγραμμα.
2. Τεμαχίζω τα μουσικά έργα σε τμήματα μικρής χρονικής διάρκειας
3. Αναπαράγω με τυχαία σειρά τα τμήματα και δημιουργώ νέα μουσικά έργα.

** version 3

Θέλω να κατασκευάσω ένα μουσικό κομμάτι που να αποτελείται από μέρη άλλων μουσικών κομματιών συναρμολογημένων με τυχαία σειρά.

* Τεκτονίδης Λευτέρης

Προτεινόμενος τίτλος εργασίας: Επίδραση ηχητικών κυμάτων στα έμβια όντα-φυτά ή ζώα καθώς και την άμεση ανταπόκριση σε κυτταρικό επίπεδο.

Τεκτονίδης Λευτερης. Θέλω να μελετήσω με ποιόν τρόπο τα ηχητικά κύματα (διαφορετικών συχνοτήτων ,εντάσεων, περιόδων έκθεσης, και απόστασης) μπορουν να επηρεάσουν την κυτταρική λειτουργία.  Επηρεάζεται το DNA ή RNA? Μπορούμε να επιταχύνουμε την κυτταρική διαίρεση και κατ επέκταση την αύξηση ενός οργανισμού? Στόχος: Να απαντήσω στην ερώτηση:  Ηχος-ίσως άλλος ένας τρόπος να χειραγωγήσουμε την φύση?

* Πέτρος Καλορίτης
** Ιδέα 1
Θέλω να εμβαθύνω και να αναπτύξω την θεματολογία του Ινδικού ρυθμού.  Hindustani [bol] / Karnatik [konnakol] [κοινές βασικές μουσικές θεωρητικές έννοιες].  [μορφολογικές / εκτελεστικές / συνθετικές έννοιες] [tal / tala] [tani avarthanam, korvai, ...].

** Ιδέα 2
Θέλω να αναπτύξω την ζωή και το έργο ενός συνθέτη.  Olivier Messiaen.  Mode de Transpositions ... "Technique de mon Langage Musical". "The Technique of my Musical Language".
** Ιδέα 3
Θέλω να εμβαθύνω στην ψυχολογική προσέγγιση εκμάθησης της μουσικής, την προσέγγιση στην καλλιτεχνική δημιουργία, καθώς /και τι αντίκτυπο συνεπάγεται η εκάστοτε ψυχολογική στάση./

* Δανάη Τσαδίμα
** Θεματική περιοχή, λέξεις κλειδιά.

Πως η εντροπία, έννοια της πολυπλοκότητας, η έννοια του τυχαίου, το χάος αποτυπώνονται στο ηχοτοπίο και με ποιον τρόπο ο μονόδρομος χρόνος επιδρά στο ακουστικό αποτύπωμα των χώρων.

** Ερωτήματα
Πως αποτυπώνεται στον ήχο;
Πως ενυπάρχει στο ηχοτοπίο;
Πως συγχέεται με το θόρυβο;
Πως με τον χρόνο δημιουργούνται ακουστικοί χώροι;

** ?????????

Με την τεχνική του feedback θέλω να προσπαθήσω να αποδώσω στο πέρας του χρόνου τον τρόπο με τον οποίο διάφοροι ήχοι προστίθενται και δημιουργούν τα ηχοτοπία.
Να παγιώσω αυτούς τους ήχους μέσω της τεχνικής Feedback και να ενισχύσω τον ήχου του εκάστοτε χώρου.
Να αναδείξω το εκάστοτε ηχοτοπίο του κάθε χώρου με την τεχνική Feedback.
Με έναν αλγόριθμο να μεταφράσω τα δεδομένα του Feedback σε κάτι νέο που θα μπορώ να επεξεργαστώ σε επόμενο χρόνο.

Μεθοδολογία: In put : Mικρόφωνο Output: Ηχεία στο χώρο σε Feedback Loop από τα ηχεία στο μικρόφωνο σε επανάληψη. Τα δεδομένα του Feedback Loop να διαβάζονται και να μεταφράζονται σε κάτι άλλο.
** Πείραμα (πειραματική διάταξη)

- Βάζω ένα μικρόφωνο στο χώρο
- Το μικρόφωνο συλλέγει το ηχοτοπίο του χώρου
- Στέλνει τον ήχο σε ηχεία
- Τα ηχεία στέλνουν τον ήχο στο μικρόφωνο
- Δημιουργείται ένα feedback loop που ενισχύει ολοένα τον ήχο του χώρου
- Τα δεδομένα που συλλέγονται μέσα από την επανάληψη σε ζωντανό χρόνο μεταφράζονται σε κάτι άλλο.

* Στέφανος Παπαχαρίτος
- Θέλω να δημιουργήσω ακολουθίες νοτών και συγχορδιών με το super collider, να τις αντιστοιχίσω στους πλανήτες του ηλιακού συστήματος και να αποδώσω το μοντέλο του Κέπλερ της Μουσικής των Σφαιρών (Harmonices Mundi).

- Θα συνδυάσω την παραπάνω μουσική κατασκευή με το περιβάλλον no input για την σύνθεση μουσικής.
